{% set version = "2.2" %}

package:
  name: charon
  version: {{ version }}

source:
  url: https://www.sandia.gov/app/uploads/sites/106/2022/06/charon-distrib-v2_2.tar.gz
  sha256: 2743f39fb14166091f1e38581f9d85379a7db178b4b2d4ce5c8411fdec727073
  
build:
  number: 2
  string: mpi_{{ mpi }}_py{{ py }}h{{ PKG_HASH }}
  script_env:
    MPI_IMPL={{ mpi }}
    TRIBITS_BASE_DIR

requirements:
  build:
    - git
    - make
    - cmake >=3.10.0
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python >=3.0.0
    - libblas
    - liblapack
    - {{ mpi }}
    - boost-cpp 1.71
    - netcdf-cxx4
    - hdf5 * mpi_{{ mpi }}_*
    - zlib
  run:
    - {{ mpi }}
    - boost-cpp
    - libopenblas
    - libnetcdf * mpi_{{ mpi }}_*
    - hdf5 * mpi_{{ mpi }}_*

about:
  home: https://charon.sandia.gov
  license: GPL-3.0
  license_file: LICENSE/Charon_LICENSE
  summary:
    TCAD simulation code from Sandia
  description:
    Charon is an open-source semiconductor device modeling code, widely referred to as a TCAD (technology computer-aided design) code, developed at Sandia National Laboratories.
